name: Build & Publish Docker Image

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3) Set up Docker Buildx (for multi‑arch, cache, etc.)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Build & push the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/lite-rpc:latest
            ghcr.io/${{ github.repository_owner }}/lite-rpc:${{ github.sha }}