name: Cargo Build, Test

on:
  push:
    branches:
      - "*"
      - "!dev"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: LiteRPC Full Build
    runs-on: ubuntu-24.04
    steps:
      - name: Install Linux Packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libssl-dev openssl protobuf-compiler

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust with caching using toolchain overrides
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          # avoid the default "-D warnings" which thrashes cache
          rustflags: ""

      - name: Use compilation cache only on non-release runs
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Set Rust caching env vars only on non-release runs
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "SCCACHE_CACHE_SIZE=1G" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Build All Targets
        run: |
          cargo build --locked --workspace --all-targets

      - name: Test All Targets
        run: |
          cargo test --workspace --all-targets
